management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
  newrelic:
    metrics:
      export:
        enabled: true
        api-key: ${NEW_RELIC_LICENSE_KEY}
        account-id: ${NEW_RELIC_ACCOUNT_ID}=
        uri: https://insights-collector.newrelic.com/v1/accounts/8065224/events
        client-provider-type: insights-api
  metrics:
    tags:
      service: geradornotafiscal
      env: ${NEW_RELIC_ENVIRONMENT:dev}

springdoc:
  api-docs:
    path: /v1/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
  show-actuator: false
